### PR TITLE
refactor: code improvements & tests

### PR DESCRIPTION
**Pull request by federico-po**
## Summary

This PR does nothing than refactor the code and add tests. No changes in functionality expected.

I'll add 2-3 more tests before implementing any feat. The next step is to create a PR with changes in how we integrate with Asana: instead of using !<id>, we'll use the PR body.

### CODE REVIEW

**Comment by federico-po** [comment]
Added you as a reviewer @maxogden . As mentioned, we should not expect any change in functionality; this just expects to add code improvements in readability and maintainability.

**Comment by maxogden** [comment]
Hey looks good. Since this is a big rewrite feel free to merge at your convenience + maintain from here on out

**Comment by federico-po** [comment]
Great! I'll probably create a branch from this one, work on the changes for the new Asana integration, and then merge both PRs :)

**Comment by federico-po** [comment]
@maxogden Is there a specific reason why we are fetching all tasks and not the particular tasks linked?

Current logic: we fetch all workspace's task and filter them by id. 

However, I've been taking a look and I'm able to get task's data with this simple request:
```js
fetch('https://app.asana.com/api/1.0/tasks/<taskId>',
    {
      method: 'GET',
      headers: {
        'content-type': 'application/json',
        Authorization:
          'Bearer <token>',
      },
    })
```

**Comment by maxogden** [comment]
if you know the exact taskId then yes that would work, but we only put a partial ID in the ticket sometimes

**Comment by federico-po** [comment]
> if you know the exact taskId then yes that would work, but we only put a partial ID in the ticket sometimes

Yeah that's a good point, I'm not 100% sure if we still want to use short ids vs entire Asana link.

```
## Summary

Some summary about the PR

// option 1
closes: https://app.asana.com/0/1200481151635978/1201186851808827/f

// option 2
closes: !1201186851808827
```

An then, once the integration runs:
```
## Summary

Some summary about the PR

closes: this Asana task
```

Do you have any particular feelings about any of the above?

**Comment by maxogden** [comment]
linking the full URL is probably the least error prone, I agree there

**Pull request merged**
